apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: zoochacha-db
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: zoochacha
    app.kubernetes.io/managed-by: argocd
    security-level: medium
data:
  DB_HOST: "mysql.zoochacha-db.svc.cluster.local"
  DB_PORT: "3306"
  DB_TYPE: "mysql" 