apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: zoochacha-db
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: zoochacha
    app.kubernetes.io/managed-by: argocd
    security-level: high
type: Opaque
stringData:
  username: "zoochacha"
  password: "ZooChacha@2024#Secure"
  root-password: "ZooChacha@2024#RootSecure" 