{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: {{ .Values.global.namespaces.db }}
type: Opaque
stringData:
  username: {{ .Values.secrets.database.username | quote }}
  password: {{ .Values.secrets.database.password | quote }}
  root-password: {{ .Values.secrets.database.rootPassword | quote }}
{{- end }} 